# Generated by Django 4.2.4 on 2023-08-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_sighting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('details', models.TextField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='finch',
            name='foods',
            field=models.ManyToManyField(to='main_app.food'),
        ),
    ]
